-- Add pros and cons arrays to topics table
ALTER TABLE topics
  ADD COLUMN IF NOT EXISTS pros text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS cons text[] NOT NULL DEFAULT '{}';

COMMENT ON COLUMN topics.pros IS 'List of advantages/strengths of the topic (generated by AI)';
COMMENT ON COLUMN topics.cons IS 'List of disadvantages/trade-offs of the topic (generated by AI)';
